version: "3.9"

services:
  db:
    image: postgres:12.12
    restart: unless-stopped
    environment:
      POSTGRES_DB: "gayclubpornofilmsdb"
      POSTGRES_USER: "gayclubpornofilmsuser"
      POSTGRES_PASSWORD: "12345"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./dbdata:/var/lib/postgresql/data/pgdata
      - ./dbinit/init.sql:/docker-entrypoint-initdb.d/db.sql
    ports:
      - "28432:5432"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U gayclubpornofilmsuser -d gayclubpornofilmsdb'"]
      interval: 10s
      timeout: 5s
      retries: 5
  java:
    build: ./javadata
    restart: unless-stopped
    depends_on:
      - db
    command: sh -c "/wait && java -jar GayClubPornoFilmsJavaTgBot.jar"
    volumes:
      - ./javadata:/root
    environment:
      - WAIT_HOSTS=db:5432
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=5
      - WAIT_HOST_CONNECT_TIMEOUT=5